### ISSUE TITLE
单引号、转义字符串语法无法识别，引发格式化错误，申请补充对单引号、转义字符的识别

### ISSUE THREAD

**Issue by 0xn0ne** [cweijan/vscode-autohotkey#104]
参考如下，代码文件链接：https://github.com/TheArkive/JXON_ahk2/tree/master

因为无法识别单引号和转义字符，字符串内的 "{"、"[" 均会被识别为语法符号，导致格式化错乱

![image](https://github.com/cweijan/autohotkey-plus/assets/16507416/6bf7a1f9-2b15-4a2d-8c15-a0c42d9cebc8)

**Comment by mark-wiemer** [comment]
Hi @0xn0ne, this project is deprecated, but I still look at issues for https://github.com/mark-wiemer/ahkpp. Feel free to post your issue there and I can see if we can fix it :)

来自 [DeepL 翻译](https://www.deepl.com/translator#en/zh/From%20DeepL%20translator%3A%20Hi%20%400xn0ne%2C%20this%20project%20is%20deprecated%2C%20but%20I%20still%20look%20at%20issues%20for%20https%3A%5C%2F%5C%2Fgithub.com%5C%2Fmark-wiemer%5C%2Fahkpp.%20Feel%20free%20to%20post%20your%20issue%20there%20and%20I%20can%20see%20if%20we%20can%20fix%20it%20%3A)： 你好 @0xn0ne，这个项目已经废弃了，但我仍在查看 https://github.com/mark-wiemer/ahkpp 的问题。请随时在那里发布您的问题，我可以看看是否能解决它:)
