### ISSUE TITLE
为什么装了插件后，保存会自动格式化？

### ISSUE THREAD

**Issue by KnIfER** [cweijan/vscode-autohotkey#105]
折磨死我了
![image](https://github.com/cweijan/autohotkey-plus/assets/11593903/5c14ba03-2704-4fd3-b6e5-d14b2fb6a6c8)

**Comment by cweijan** [comment]
扩展不会自动格式化, 检查你的setting.json

**Comment by mark-wiemer** [comment]
@KnIfER check out [AutoHotkey++](https://github.com/mark-wiemer-org/ahkpp), a fork of this repo, and open an issue there if you're having the same problem :)

请访问本软件源的分叉版 [AutoHotkey++](https://github.com/mark-wiemer-org/ahkpp)，如果遇到同样的问题，请在那里提交问题。:)
