### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by mark-wiemer** [cweijan/vscode-autohotkey#106]
Hi, I notice this extension is still getting a lot of installs, but bugs haven't been addressed for years. If you're not planning to work on this any more, would you mind marking it as deprecated so that new AHK users know to use AHK++ instead? AHK++ now has v2 support along with dozens of bugfixes and some other new features.

Thanks again for all your work :)

**Comment by cweijan** [comment]
Hi, the reason I didn't deprecate it before was because I relied on ahk+'s formatting, and ahk++ was not consistent with this extension, but now I've switched to Mac OS, so you can mark this extension as deprecated.

**Comment by mark-wiemer** [comment]
Thanks :) Would you mind endorsing my extension as replacement to yours, or would you prefer it VS Code marketplace simply says "This extension is deprecated" without recommending any other extension?

**Comment by cweijan** [comment]
OK, you can use ahk++ as an alternative.

**Comment by mark-wiemer** [comment]
For reference, I used https://github.com/microsoft/vscode-discussions/discussions/1 to mark this extension deprecated, you can probably use the same thread if you'd like to mark it un-deprecated (ref https://github.com/mark-wiemer/ahkpp/issues/603)

**Comment by cweijan** [comment]
Thanks, I have marked Autohotkey Plus as AHK V1 only.
