### ISSUE TITLE
Trying to change display name

### ISSUE THREAD

**Issue by usernamehw** [cweijan/vscode-autohotkey#11]
It's weird that your extension is 5th on the query `autohotkey` in marketplace:

![Screenshot (154)](https://user-images.githubusercontent.com/9638156/77320737-2973ec00-6d22-11ea-8e6b-fef45c44e68d.png)

By installs and rating I think it should be 2nd.

Could you try to change display name to be 2 words (from `AutoHotkeyPlus` to `AutoHotkey Plus`)

https://github.com/cweijan/vscode-autohotkey/blob/307a1a749042eb6eb6b5f42c5389142d10e0d558/package.json#L3

Don't know if it's going to work, but it just might.

**Comment by cweijan** [comment]
It's possible, I try change name in next update.

**Comment by cweijan** [comment]
It does become 2nd, interesting

**Comment by usernamehw** [comment]
Now you just need 80k more installs to get to the first place ⬆

**Comment by usernamehw** [comment]
Added to the Awesome list: https://github.com/viatsko/awesome-vscode/pull/303
