### ISSUE TITLE
Improve the project with script interactions

### ISSUE THREAD

**Issue by Denis-net** [cweijan/vscode-autohotkey#14]
Hi @cweijan !😊👋🏼
I think this should be the definitive ahk extension.
The others are buggy as hell.
If you want to take a look at this project you'll find something usefull, do whatever you want with it:
https://send.firefox.com/download/68989af00a8562df/#TQdL2wWlkb--H0EhvtKuNg
Best

**Comment by cweijan** [comment]
Ok. Thank you for sharing.
Why did you log out of your previous github account, so crazy.

**Comment by Denis-net** [comment]
I'm not sure about what to say:
I want to take a kind of "break".
Everybody has its wars and daemons, but i'm feeling alone more than ever...
I know i overreacted, but I'm in a chaotic state of mind and i need to reboot all my systems before taking next steps more clearer.
We should strive for quality, but on these days i don't feel like i'm able to deliver it.
I have to prioritize the most important things, first.

About Ahk: my initial idea was to group existing extensions built by the community, each of them specialized in one thing but i wasn't able to join them, everybody just copy and paste existing project doing and redoing the same things with the only effect of creating a big crappy vscode support and they don't want to mantain or fix it...
I'm just an unsupported developer who fights against his bad thoughts.
You're extension is the best but i just want not to see two play buttons at the top, this made me go crazy.😅
I don't want contrasts, I just want to do the best things as long as I can.
At the moment I'm suffering and not able to focus, I hope this is the right thing to do.
We should revert to the origin in order to go to the next level and not simply trying to reivent the wheel.

Wish you best !

**Comment by cweijan** [comment]
You are emotional man, bless you.
