### ISSUE TITLE
Suggestions issue

### ISSUE THREAD

**Issue by ankitkraken** [cweijan/vscode-autohotkey#4]
After installing the extension, I get suggestions only for the functions that I have defined. When I uninstall the extension I get everything the variables, functions etc.

Do I have to do any settings in order to get this fixed or is this a bug?

**Comment by cweijan** [comment]
Conflict with the original complection, I'm looking for a solution

**Comment by cweijan** [comment]
I disable plugin complection, update to 2.1.1 version solve this problem.

**Comment by ankitkraken** [comment]
Yes. Update fixed the issue. Thanks.
