### ISSUE TITLE
请问如何以管理员权限调试脚本？

### ISSUE THREAD

**Issue by Lingzhou314** [cweijan/vscode-autohotkey#74]
大佬，我用ctrl+f9运行脚本的方式有效果，但是f9调试的时候却没用，是不是因为管理员权限的问题，要怎么启用管理员调试权限？

比如我写了个游戏脚本，每隔两秒按一下F4，但是调试的时候没有效果，只能运行脚本才行：
```
Loop
{
    ControlSend,, {F4}, Warcraft III
    Sleep, 2000
}
Return
```

**Comment by CoffeeChaton** [comment]
![Snipaste_2022-02-12_21-40-15](https://user-images.githubusercontent.com/63182963/153713713-f38b9157-d19b-44ea-a879-0a610fcd224f.png)

使用管理員模式啟動vscode

**Comment by mark-wiemer** [comment]
Hi @Lingzhou314 , I'm happy to help but I only speak English and French. Does this seem like an OK translation of your question:

> I can run the script with ctrl+f9, but I can't debug it with f9. Is it because I need administrator privileges? How do I enable administrator debugging privilege?

> For example, I wrote a game script and pressed F4 every two seconds, but it doesn't work when debugging, I can only run the script.

**Comment by mark-wiemer** [comment]
Closing as stale. @Lingzhou314 you're welcome to re-open when you provide more details. I monitor all bugs, closed or open :)
