### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by mark-wiemer** [cweijan/vscode-autohotkey#78]
It hasn't been touched in over a year, and several bugs have been fixed by my fork. It may be best for users to know that this extension is deprecated. You could point to my extension, [AutoHotkey Plus Plus](https://marketplace.visualstudio.com/items?itemName=mark-wiemer.vscode-autohotkey-plus-plus), as a replacement.

See [how to mark extensions as deprecated](https://code.visualstudio.com/updates/v1_68#_deprecated-extensions) and [my request to deprecate this extension](https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-3081884)

If you're able to come back to this project, or transfer ownership to someone willing to maintain it (like me 😉) I'll happily rescind the request.

For now, it seems users are not getting a great experience with your extension, and it doesn't look like it'll improve any time soon.

**Comment by mark-wiemer** [comment]
Hey @cweijan , I'm hoping we can follow up here. I think everyone would have a better experience if they knew right away that this extension was no longer actively maintained. Please let me know if you're still working on this. If not, it's probably best to deprecate so users are aware of the bugfixes and additional features in my extension

**Comment by cweijan** [comment]
Hi, I do no longer maintain this extension and block the activity of this repository, so I didn't receive your issue.

I'm still using this extension though, as AutoHotkey Plus Plus doesn't seem to have changed much.

**Comment by cweijan** [comment]
Thanks for your attention, I will gradually restart the maintenance work.
