### ISSUE TITLE
Working together with AutoHotkey Plus Plus

### ISSUE THREAD

**Issue by mark-wiemer** [cweijan/vscode-autohotkey#82]
Hi @cweijan , my fork of your extension now has about 50,000 installs. I originally started developing AHK++ to replace AHK+ back when you posted a deprecation notice. Now that you've mentioned you'll be continuing development on this project, I'm wondering what your thoughts are on collaboration. I can work to push some of the changes exclusive to AHK++ into AHK+ so we can get parity.

But it'd be best if end-users only had one AHK language support extension that they needed to install and maintain.

What are your plans for future maintenance of this project? Do you have ideas for new features that you'd like to add? How frequently will you be writing code to fix bugs or add configuration options requested by the community?

I'd love to work together in whatever way works best for everyone.

**Comment by cweijan** [comment]
Hir sir, I don't have a good proposal for collaboration, do you have any ideas? If you want two extensions to be merged, there is a problem with how to deal with two github repositories.

when I posted the deprecation notice, Autothotkey plus still has a lot of features to improve, such as debugger, parser and IntelliSense, but ahk++ has been maintained for two years, it has no breaking changes to the core features. it's not enough, so I can't make it a replacement.

I think the purpose of the extension is not to solve github issues, but to make language features more complete, which is where I plan to improve, I will only do it when I'm not busy.

**Comment by mark-wiemer** [comment]
That makes sense. I think we should maintain one GitHub repository and one extension in the long run, and I think it should be yours. 

I wasn't able to contribute large features, no, I just made some minor improvements in my free time. So it should be easy to merge the changes in AHK++ into AHK+.

Hopefully with one GitHub repo and extension it'll be easier to make improvements!

I'll start opening some pull requests now :)

**Comment by cweijan** [comment]
Thanks for your understanding, I transferred the repository to [VSCode Autohotkey](https://github.com/vscode-autohotkey) and sent you an invitation email, after you join you can commit code directly to this repository.
